name: "Build a vellum package"
description: Build a vellum package
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  path:
    description: Folder containing the VELBUILD file and any artifacts
    required: false
    default: .
  action:
    description: Action to run
    required: false
    default: all
  version:
    description: Version of vbuild to use
    required: false
    default: latest
  arch:
    description: What architecture to build for
    required: false
    default: noarch
  driver:
    description: Which driver to use. Can be podman or docker
    required: false
    default: podman
runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        if [ "$VBUILD_DRIVER" != 'podman' ] && [ "$VBUILD_DRIVER" != 'docker' ];then
          echo "Error: invalid driver: $VBUILD_DRIVER"
          exit 1
        fi
        if [ ! -d "$src_path" ];then
          echo "Error: Path does not exist: $src_path"
          exit 1
        fi
      env:
        VBUILD_DRIVER: ${{ inputs.driver }}
        src_path: ${{ inputs.path }}
    - name: Download vbuild
      uses: ./install
      with:
        version: ${{ inputs.version }}
    - name: Run vbuild
      shell: bash
      run: |
        set -e
        if [ "$VBUILD_DRIVER" == 'podman' ];then
          echo "Starting podman service..."
          sudo mkdir -p /run/user/"$(id -u)"/podman
          socketdir=/run/user/"$(id -u)"/podman
          sudo chown "$(id -u):$(id -g)" "$socketdir"
          podman system service --time 0 unix://"$socketdir/podman.sock" &
          tries=0
          while [ ! -S "$socketdir/podman.sock" ] && [ $tries -lt 60 ];do
            tries=$(( tries + 1 ))
            sleep 0.1
          done
        fi
        echo "Running vbuild..."
        vbuild -C "${{ inputs.path || '.' }}" "${{ inputs.action || 'all' }}"
        if [ "$VBUILD_DRIVER" == 'podman' ];then
          echo "Stopping podman service..."
          kill $(jobs -p) || true
        fi
      env:
        VBUILD_DRIVER: ${{ inputs.driver }}
        CARCH: ${{ inputs.arch }}
