name: Install vbuild
description: Install vbuild
author: Eeems
branding:
  icon: tablet
  color: white
inputs:
  version:
    description: Version of vbuild to use
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Download vbuild
      shell: bash
      run: |
        set -e
        if [[ "$version" == "latest" ]];then
          part="$version/download"
          name=vbuild-x86_64-glibc
        else
          part="download/$version"
          if printf '%s\n' "${{ inputs.version }}" "0.0.22" | sort -C -V; then
            name=vbuild-vbuild-ubuntu
          else
            name=vbuild-x86_64-glibc
          fi
        fi
        curl \
          --location \
          "https://github.com/Eeems/vbuild/releases/$part/$name" \
          --output /usr/local/bin/vbuild
        chmod +x /usr/local/bin/vbuild
        file /usr/local/bin/vbuild
      env:
        version: ${{ inputs.version }}
